name: tubes_semester_6
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3  
  google_fonts: ^6.2.1
  image: ^4.3.0
  image_picker: ^1.1.2
  lottie: ^2.2.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  tflite_flutter: ^0.11.0
  vs_scrollbar: ^1.0.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/